In [2]:
# CSV파일
## pandas.read_csv("파일 경로(이름)")

import pandas as pd
import os

os.listdir("./data")

['read_csv_sample.csv', 'test.txt']

In [3]:
file_path = "./data/read_csv_sample.csv"
print(file_path)

./data/read_csv_sample.csv

In [4]:
file_path2 = os.path.join("data", "read_csv_sample.csv")
print(file_path2)

data\read_csv_sample.csv

In [8]:
df1 = pd.read_csv(file_path)
df1
type(df1)
df1

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [7]:
df2 = pd.read_csv(file_path, header=None)
df2

    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9

In [10]:
df3 =  pd.read_csv(file_path, index_col=None)
df3

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [11]:
df4 = pd.read_csv(file_path, index_col="c0")
df4

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9