In [2]:
# 평균값

import pandas as pd

df = pd.read_csv("./data/auto-mpg.csv", header=None)

df.columns = [
    "mpg", "cylinder", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"
]

df.head()

,mpg,cylinder,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [3]:
df.mean(numeric_only=True)

mpg               23.514573
cylinder           5.454774
displacement     193.425879
weight          2970.424623
acceleration      15.568090
model year        76.010050
origin             1.572864
dtype: float64

In [4]:
df["horsepower"].info()

<class 'pandas.Series'>
RangeIndex: 398 entries, 0 to 397
Series name: horsepower
Non-Null Count  Dtype
--------------  -----
398 non-null    str
dtypes: str(1)
memory usage: 3.2 KB

In [5]:
print(round(df["mpg"].mean(), 2))
print(df["mpg"].mean().round(2))

23.51
23.51

In [6]:
# 중앙값 

print(df.median(numeric_only=True))
print(df["mpg"].median())

mpg               23.0
cylinder           4.0
displacement     148.5
weight          2803.5
acceleration      15.5
model year        76.0
origin             1.0
dtype: float64
23.0

In [7]:
# 최대값
df.max(numeric_only=True)

# 최소값
df.min(numeric_only=True)

mpg                9.0
cylinder           3.0
displacement      68.0
weight          1613.0
acceleration       8.0
model year        70.0
origin             1.0
dtype: float64

In [8]:
# 표준편차 
df.std(numeric_only=True)

mpg               7.815984
cylinder          1.701004
displacement    104.269838
weight          846.841774
acceleration      2.757689
model year        3.697627
origin            0.802055
dtype: float64

In [9]:
## 상관계수
df.corr(numeric_only=True)

,mpg,cylinder,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinder,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000

In [10]:
df["horsepower"].info()

<class 'pandas.Series'>
RangeIndex: 398 entries, 0 to 397
Series name: horsepower
Non-Null Count  Dtype
--------------  -----
398 non-null    str
dtypes: str(1)
memory usage: 3.2 KB

In [12]:
df["horsepower"].value_counts()

horsepower
150.0    22
90.00    20
88.00    19
110.0    18
100.0    17
         ..
77.00     1
132.0     1
64.00     1
116.0     1
82.00     1
Name: count, Length: 94, dtype: int64

In [14]:
print(df["horsepower"].min())
print(df["horsepower"].max())

100.0
?

In [15]:
print(df["name"].min())
print(df["name"].max())

amc ambassador brougham
vw rabbit custom

In [19]:
data = ["100", "900", "001", "2", " ", "?"]
df = pd.Series(data)
print(df.min())
print(df.max())

?