In [1]:
import pandas as pd

data = {
    "c1": ['a', 'a', 'b', 'a', 'b'], 
    'c2': [1, 1, 1, 2, 2], 
    'c3': [1, 1, 2, 2, 2]
}

df = pd.DataFrame(data)
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [ ]:
## duplicated() 매서드
df_dup_first = df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [3]:
df_dup_last = df.duplicated(keep="last")
df_dup_last

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [4]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [6]:
df["c2"].duplicated()

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [8]:
# 중복 데이터 제거 
print(df)
df2 = df.drop_duplicates()
print()
print(df2)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [10]:
print(df)
df2 = df.drop_duplicates(keep="last")
print()
print(df2)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

  c1  c2  c3
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [11]:
print(df)
df4 = df.drop_duplicates(keep=False)

print()
print(df4)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

  c1  c2  c3
2  b   1   2
3  a   2   2
4  b   2   2

In [12]:
print(df)
df5 = df.drop_duplicates(subset=['c2', 'c3'])
print()
print(df5)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [13]:
print(df)
df6 = df.drop_duplicates(subset=['c2', 'c3'], keep=False)
print()
print(df6)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

  c1  c2  c3
2  b   1   2